### ISSUE TITLE
Calendar month day is distorted

### ISSUE THREAD

**Issue by laurensiusadi** [yuanfux/vue-metro-tile#1]
![firefox_2018-10-02_10-46-30](https://user-images.githubusercontent.com/5661040/46328243-7183e800-c630-11e8-86d0-67c726c0ae1f.png)

CSS class: `.calendar .calendar-month-day`
Cause: `transform: scale(1.5,2)`

Should be: `transform: scale(1.75)`

![firefox_2018-10-02_10-48-33](https://user-images.githubusercontent.com/5661040/46328304-bc9dfb00-c630-11e8-8918-07c2bf87be59.png)

**Comment by yuanfux** [comment]
good suggestion, will fix soon
