### ISSUE TITLE
how to make the child element get focus?

### ISSUE THREAD

**Issue by xihuanhh** [yuanfux/vue-metro-tile#2]
hi, i want to put some element like button in slot, but it can not get focused,  i has just use Vue.js for first time, could you give some opinions, appreciate for that.

my slot like this
`            <div slot="front" class="front animated fadeIn 1s" :style="appBgColorSelect(item)">
              <h2 class="main-name">{{ item.name }}</h2>
              <div class="sub-name">{{ item.desc ? item.desc : '' }}</div>
              <el-button class="bg-green-hover"  size='mini' type="danger" icon="el-icon-delete"
                         circle @click="remove(item._id)">
              </el-button>
            </div>`

i expect the `<el-button>` click and focus is enabled

**Comment by yuanfux** [comment]
Sorry for the late reply, but this should be fixed in the new patch 1.0.4.

**Comment by xihuanhh** [comment]
@yuanfux  appreciate for you great job !
